# Generated by Django 5.2.1 on 2025-05-10 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the book.', unique=True)),
                ('title', models.CharField(help_text='Title of the book.', max_length=128, verbose_name='Title')),
                ('author', models.CharField(help_text='Author of the book.', max_length=128, verbose_name='Author')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the page.', unique=True)),
                ('number', models.PositiveIntegerField(help_text='Number of the page.', verbose_name='Page number')),
                ('content', models.TextField(help_text='Content of the page.', max_length=2048, verbose_name='Content')),
                ('book', models.ForeignKey(help_text='Book to which the page belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.book', verbose_name='Book')),
            ],
        ),
    ]
